name: Stale Pull Requests

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stale:
    name: Clean up stale pull requests
    runs-on: ubuntu-latest
    steps:
      - name: Stale PR
        uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 21
          days-before-close: 7
          remove-stale-when-updated: true
          stale-pr-label: "stale"
          exempt-pr-labels: "no-stale"
          stale-pr-message: >
            There hasn't been any activity on this pull request recently, and in order to prioritize active work, it has
            been marked as stale. This PR will be closed and locked in 7 days if no further activity occurs. Thank you
            for your contributions!
          only: pr  
